name: Deploy nhl-stats-react

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy react app
    runs-on: ubuntu-latest
    steps:
    - name: Pull changes from master
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        port: 22
        script: |
          cd /home/sstoveld/dev/nhl-stats-react
          git pull origin master
          docker build -f Dockerfile -t debaser19/nhl_stats:prod .
          docker run -d --restart always --rm -p 1337:80 nhl_stats:prod