name: Deploy nhl-stats-react

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy react app
    runs-on: ubuntu-latest
    steps:
    - name: Pull changes from master
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        user: sstoveld
        key: ${{ secrets.SSH_SECRET }}
        port: 22
        command: |
          cd /home/sstoveld/dev/nhl-stats-react
          git pull origin master
          npm install
          npm run build
          cp -R build /var/www/html